[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect non-www to www
[[redirects]]
  from = "http://adaa-foundation.org/*"
  to = "https://www.adaa-foundation.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://adaa-foundation.org/*"
  to = "https://www.adaa-foundation.org/:splat"
  status = 301
  force = true
